### PR TITLE
Update plugin parent POM

### PR DESCRIPTION
**Pull request by basil**

### CODE REVIEW

**Comment by basil** [comment]
@jenkinsci/okhttp-api-plugin-developers A release of this would facilitate Java 17 PCT testing.

**Comment by timja** [comment]
@car-roll possible to take care of this please?

**Comment by basil** [comment]
@car-roll Gentle ping. Refreshing this plugin would help us remove a hack from BOM/PCT:

https://github.com/jenkinsci/bom/blob/77b8d3b46a373aeed71217e9b5d4e7a218e42d5f/pct.sh#L69-L81

**Review by car-roll — APPROVED** [review]
sorry for the delay, missed the multiple pings 😓 
LGTM

**Pull request merged**
